# Generated by Django 4.0.3 on 2022-08-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('password1', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobno', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='photo/')),
                ('file', models.FileField(upload_to='file/')),
            ],
        ),
    ]
