# Generated by Django 4.0.3 on 2022-09-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfectapp', '0002_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='finalsubmit',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('qno', models.IntegerField()),
                ('subject', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=40)),
                ('op', models.CharField(max_length=10)),
            ],
        ),
    ]
