# Generated by Django 4.0.3 on 2022-09-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfectapp', '0004_alter_finalsubmit_qno_alter_finalsubmit_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='finalsubmit',
            new_name='dinalsubmit',
        ),
    ]
