# Generated by Django 4.0.3 on 2022-09-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfectapp', '0005_rename_finalsubmit_dinalsubmit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'score',
            },
        ),
        migrations.AlterModelTable(
            name='dinalsubmit',
            table='finaldata',
        ),
    ]
